{{ if .Values.networkingStack.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: networking-stack
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/adarlan/k8slab.git
    path: helm-charts/networking-stack
    targetRevision: master
    helm:
      releaseName: networking
      valuesObject:
{{ toYaml .Values.networkingStack.values | indent 8 }}

  destination:
    name: in-cluster
    namespace: networking

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

{{ end }}
