{{ if .Values.pythonCrud.enabled }}
{{ range .Values.pythonCrud.applications }}

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: {{ .name }}
  namespace: argocd
  labels:
    selection: application-templates
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/adarlan/k8slab.git
    targetRevision: {{ .chartVersion }}
    path: deployable-apps/python-crud

    helm:
      releaseName: {{ .name }}
      valuesObject:
{{ toYaml .values | indent 8 }}

  destination:
    name: in-cluster
    namespace: {{ .namespace }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
{{ end }}
{{ end }}
