apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: crudify
  namespace: argocd
  # labels:
  #   selection: application-templates
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/adarlan/k8slab.git
    targetRevision: master
    path: deploy/crudify

    helm:
      releaseName: crudify
      valuesObject:
        ingress:
          enabled: true
          host: crud.localhost
          basePath: ""
        serviceMonitor:
          enabled: true
          prometheusRelease: monitoring-stack
        microservices:
          - microserviceName: item-creator
            microserviceReplicas: 1
            clientMaxIterations: 10
            clientIntervalInMinutes: 1
          - microserviceName: item-reader
            microserviceReplicas: 1
            clientMaxIterations: 10
            clientIntervalInMinutes: 2
          - microserviceName: item-updater
            microserviceReplicas: 1
            clientMaxIterations: 10
            clientIntervalInMinutes: 3
          - microserviceName: item-deleter
            microserviceReplicas: 1
            clientMaxIterations: 10
            clientIntervalInMinutes: 4

  destination:
    name: in-cluster
    namespace: crudify

  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
