environment: local
greetingMessage: Hello, World!
route: localhost
replicas: 1

stableImageTag: master
# unstableImageTag: develop
unstableImageTag: master

_servicePortNumber: 80

ingress:
  enabled: false

serviceMonitor:
  enabled: false
