userRoles:

- name: cluster-administrator
  permissions:
    # TODO remove write permission for namespaces, resourcequotas, limitranges, serviceaccounts?, roles, rolebindings, clusterroles, clusterrolebindings
  - apiGroup: "*"
    resources: ["*"]
    accessMode: readwrite
  users:
  - Jane Ops

serviceAccounts:

- name: namespace-provisioning
  permissions:
  - accessMode: readwrite
    apiGroup: ""
    resources:
    - namespaces
    - resourcequotas
    - limitranges

- name: namespace-rbac
  permissions:
  - accessMode: readonly
    apiGroup: ""
    resources:
    - namespaces
  - accessMode: readwrite
    apiGroup: ""
    resources:
    - serviceaccounts
    - secrets
  - accessMode: readwrite
    apiGroup: rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings

- name: cluster-tools
  permissions:
    # Note: it needs full access to install argocd
  - apiGroup: "*"
    resources: ["*"]
    accessMode: readwrite
