apiVersion: v1
kind: Service
metadata:
  name: item-creator
  labels:
    app: item-creator
spec:
  selector:
    app: item-creator
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
