apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-creator
spec:
  replicas: 5
  selector:
    matchLabels:
      app: item-creator
  template:
    metadata:
      labels:
        app: item-creator
    spec:
      containers:
      - name: item-creator
        image: adarlan/python-crud-item-creator:master
        ports:
        - name: web
          containerPort: 80
        - name: metrics
          containerPort: 9100
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 150Mi
            cpu: 150m
        livenessProbe:
          httpGet:
            port: web
            path: /healthz
          initialDelaySeconds: 30
          periodSeconds: 10
