apiVersion: apps/v1
kind: StatefulSet

{{ $app := printf "%s-mongodb" .Release.Name }}

metadata:
  name: {{ $app }}
  labels:
    app: {{ $app }}

spec:
  selector:
    matchLabels:
        app: {{ $app }}

  serviceName: {{ $app }} # $(service name).$(namespace).svc.cluster.local

  replicas: 1          # by default is 1
  minReadySeconds: 30  # by default is 0

  template:
    metadata:
      labels:
        app: {{ $app }}
    spec:
      terminationGracePeriodSeconds: 10

      containers:
      - name: mongo
        image: docker.io/mongo:7.0

        ports:
        - name: mongodb
          containerPort: 27017

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        - name: MONGO_INITDB_DATABASE
          value: default

        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

        # volumeMounts:
        # - name: www
        #   mountPath: /usr/share/nginx/html

#   volumeClaimTemplates:
#   - metadata:
#       name: www
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       storageClassName: "my-storage-class"
#       resources:
#         requests:
#           storage: 1Gi
