namespaces:

- name: argocd
  # hardResourceQuota:
  #   pods: "10"
  #   requests.cpu: "0.25"
  #   limits.cpu: "1"
  #   requests.memory: 256Mi
  #   limits.memory: 1Gi

- name: development
  hardResourceQuota:
    pods: "5"
    requests.cpu: 50m
    requests.memory: 128Mi
    limits.cpu: 250m
    limits.memory: 512Mi

- name: staging
  hardResourceQuota:
    pods: "10"
    requests.cpu: 100m
    requests.memory: 256Mi
    limits.cpu: 500m
    limits.memory: 1Gi

- name: production
  hardResourceQuota:
    pods: "20"
    requests.cpu: 200m
    requests.memory: 512Mi
    limits.cpu: 1000m
    limits.memory: 2Gi

- name: crudify
  hardResourceQuota:
    pods: "50"
    requests.cpu: 500m
    limits.cpu:   2000m
    requests.memory: 512Mi
    limits.memory:   2Gi

- name: monitoring
  # hardResourceQuota:
  #   pods: "50"
  #   requests.cpu: "0.25"
  #   limits.cpu: "1"
  #   requests.memory: 256Mi
  #   limits.memory: 1Gi

- name: ingress
#   hardResourceQuota:
#     pods: "10"
#     requests.cpu: "0.05"
#     limits.cpu: "0.5"
#     requests.memory: 128Mi
#     limits.memory: 512Mi

- name: trivy
  # hardResourceQuota:
  #   pods: "10"
  #   requests.cpu: "0.05"
  #   limits.cpu: "0.5"
  #   requests.memory: 128Mi
  #   limits.memory: 512Mi
