apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: hello-world
  namespace: argocd

spec:
  generators:
  - list:
      elements:
      - environment: development
        targetRevision: master
        appName: hello-world-dev
        destinationCluster: in-cluster
        destinationNamespace: development
        greetingMessage: Hello, Development Environment!
        ingressHost: dev.localhost
        ingressPath: /hello
        replicas: "3"

      - environment: staging
        targetRevision: master
        appName: hello-world-stg
        destinationCluster: in-cluster
        destinationNamespace: staging
        greetingMessage: Hello, Staging Environment!
        ingressHost: stg.localhost
        ingressPath: /hello
        replicas: "9"

      - environment: production
        targetRevision: master
        appName: hello-world-prd
        destinationCluster: in-cluster
        destinationNamespace: production
        greetingMessage: Hello, Production Environment!
        ingressHost: hello.localhost
        ingressPath: /
        replicas: "36"

  template:
    metadata:
      name: "{{appName}}"
      namespace: argocd
      labels:
        app: "{{appName}}"
    spec:
      project: default

      source:
        repoURL: https://github.com/adarlan/k8slab.git
        path: helm-charts/hello-world
        targetRevision: "{{targetRevision}}"
        helm:
          releaseName: "{{appName}}"
          # valueFiles:
          # - values-{{profile}}.yaml
          parameters:
          - { name: environment,     value: "{{environment}}" }
          - { name: greetingMessage, value: "{{greetingMessage}}" }
          - { name: ingressHost,     value: "{{ingressHost}}" }
          - { name: ingressPath,     value: "{{ingressPath}}" }
          - { name: replicas,        value: "{{replicas}}" }

      destination:
        name: "{{destinationCluster}}"
        namespace: "{{destinationNamespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
