apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring-stack
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  # TODO project: cluster-toolkit

  source:
    repoURL: https://github.com/adarlan/k8slab.git
    path: helm-charts/monitoring-stack
    targetRevision: master
    helm:
      releaseName: monitoring-stack
      # valueFiles:
      # - values-kind.yaml

  destination:
    name: in-cluster
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
