apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/adarlan/k8slab.git
    targetRevision: HEAD
    path: app-manifests/python-app
  destination:
    server: https://kubernetes.default.svc
    namespace: python-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
