kube-prometheus-stack:
  enabled: true
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - grafana.localhost
      path: /
    
    ## Configure additional grafana datasources (passed through tpl)
    ## ref: http://docs.grafana.org/administration/provisioning/#datasources
    additionalDataSources:
    - name: loki
      # access: proxy
      # basicAuth: true
      # basicAuthPassword: pass
      # basicAuthUser: daco
      editable: false
      # jsonData:
      #     tlsSkipVerify: true
      orgId: foobar
      type: loki
      url: http://loki-gateway:80
      version: 1

  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      hosts:
        - prometheus.localhost
      pathType: ImplementationSpecific
      paths:
        - /(.*)

grafana:
  enabled: false
  datasources: {}

loki:
  enabled: true
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  singleBinary:
    replicas: 1

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki-gateway/loki/api/v1/push
        tenant_id: foobar

# kube-prometheus-stack:
#   # prometheus:
#   #   service:
#   #     type: NodePort
#   #     nodePort: ${prometheusNodePort}
#   grafana:
#     enabled: false
#     # service:
#     #   type: NodePort
#     #   nodePort: ${grafanaNodePort}

# grafana:
#   datasources: {}
#   #  datasources.yaml:
#   #    apiVersion: 1
#   #    datasources:
#   #    - name: Prometheus
#   #      type: prometheus
#   #      url: http://prometheus-prometheus-server
#   #      access: proxy
#   #      isDefault: true
#   #    - name: CloudWatch
#   #      type: cloudwatch
#   #      access: proxy
#   #      uid: cloudwatch
#   #      editable: false
#   #      jsonData:
#   #        authType: default
#   #        defaultRegion: us-east-1
#   #    deleteDatasources: []
#   #    - name: Prometheus
