controller:
  hostPort:
    enabled: true
  terminationGracePeriodSeconds: 0
  service:
    type: "NodePort"
  watchIngressWithoutClass: true
  nodeSelector:
    ingress-ready: "true"
  tolerations:
  - effect: "NoSchedule"
    key: "node-role.kubernetes.io/master"
    operator: "Equal"
  - effect: "NoSchedule"
    key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
  publishService:
    enabled: false
  extraArgs:
    publish-status-address: "localhost"
  resources:
    requests:
      cpu: 100m
      memory: 100M
    limits:
      cpu: 150m
      memory: 200M
  admissionWebhooks:
    createSecretJob:
      resources:
        requests:
          cpu: 100m
          memory: 100M
        limits:
          cpu: 150m
          memory: 200M
    patchWebhookJob:
      resources:
        requests:
          cpu: 100m
          memory: 100M
        limits:
          cpu: 150m
          memory: 200M
