apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world
data:
  index.html: <h1>Hello, World!</h1>
  nginx.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
      location /metrics {
        stub_status on;
        access_log off;
      }
    }
