apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world # the service monitor will use it to select this service
spec:
  selector:
    app: hello-world # selecting the pods with this label
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
