# <serviceAccounts>
{{ range .Values.serviceAccounts }}
{{ $serviceAccountName := .name }}
{{ $permissions := .permissions }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: cluster-operators

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ $serviceAccountName }}
  namespace: cluster-operators
  annotations:
    kubernetes.io/service-account.name: {{ $serviceAccountName }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $serviceAccountName }}

rules:

# <permissions>
{{ range $permissions }}
{{ $apiGroup := .apiGroup }}
{{ $resources := .resources }}
{{ $accessMode := .accessMode }}

- apiGroups:
  - "{{ $apiGroup }}"

  resources:
  {{ range $resources }}
  - "{{ . }}"
  {{ end }}

  {{ if eq $accessMode "readwrite" }}
  verbs: ["*"]
  {{ else }}
  verbs: ["get", "list", "watch"]
  {{ end }}

{{ end }}
# </permissions>

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: {{ $serviceAccountName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: cluster-operators

{{ end }}
# </serviceAccounts>
