# <userRoles>
{{ range .Values.userRoles }}
{{ $roleName := .name }}
{{ $permissions := .permissions }}
{{ $users := .users }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $roleName }}

rules:

# <permissions>
{{ range $permissions }}
{{ $apiGroup := .apiGroup }}
{{ $resources := .resources }}
{{ $accessMode := .accessMode }}

- apiGroups:
  - "{{ $apiGroup }}"

  resources:
  {{ range $resources }}
  - "{{ . }}"
  {{ end }}

  {{ if eq $accessMode "readwrite" }}
  verbs: ["*"]
  {{ else }}
  verbs: ["get", "list", "watch"]
  {{ end }}

{{ end }}
# </permissions>

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $roleName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $roleName }}

subjects:
{{ range $users }}
- kind: User
  name: {{ . }}
{{ end }}

{{ end }}
# </userRoles>
