{{- $presets := .Values.presets }}

{{- range .Values.namespaces }}

{{- $computePreset := .computePreset | default "standardCompute" }}
{{- $computeResources := (hasKey . "computeResources") | ternary .computeResources (get $presets $computePreset) }}

{{- $persistencePreset := .persistencePreset | default "standardPersistence" }}
{{- $persistenceResources := (hasKey . "persistenceResources") | ternary .persistenceResources (get $presets $persistencePreset) }}

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
spec:
  hard:
    pods:            "{{ $computeResources.maxPodCount }}"
    requests.cpu:    "{{ $computeResources.cpu.requests.quota }}"
    requests.memory: "{{ $computeResources.memory.requests.quota }}"
    limits.cpu:      "{{ $computeResources.cpu.limits.quota }}"
    limits.memory:   "{{ $computeResources.memory.limits.quota }}"
    persistentvolumeclaims: "{{ $persistenceResources.maxPvcCount }}"
    requests.storage:       "{{ $persistenceResources.storage.quota }}"

{{- end }}
