# <serviceAccounts>
{{ range .Values.serviceAccounts }}
{{ $serviceAccountName := .name }}
{{ $permissions := .permissions }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $serviceAccountName }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $serviceAccountName }}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $serviceAccountName }}
  annotations:
    kubernetes.io/service-account.name: {{ $serviceAccountName }}

# <ClusterRole>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $serviceAccountName }}

rules:

# <permissions>
{{ range $permissions }}
{{ $apiGroup := .apiGroup }}
{{ $resources := .resources }}
{{ $accessMode := .accessMode }}

- apiGroups:
  - "{{ $apiGroup }}"

  resources:
  {{ range $resources }}
  - "{{ . }}"
  {{ end }}

  {{ if eq $accessMode "readwrite" }}
  verbs: ["*"]
  {{ else }}
  verbs: ["get", "list", "watch"]
  {{ end }}

{{ end }}
# </permissions>

# </ClusterRole>

# <ClusterRoleBinding>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: {{ $serviceAccountName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: {{ $serviceAccountName }}
# </ClusterRoleBinding>

# <Role>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $serviceAccountName }}
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs: ["*"]
# </Role>

# <RoleBinding>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $serviceAccountName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: {{ $serviceAccountName }}
# </RoleBinding>

{{ end }}
# </serviceAccounts>
