pythonCrud:
  enabled: true # if you disable the application, it won't be deleted, because it won't be applied
  applications:
  - name: python-crud
    chartVersion: master
    namespace: python-crud
    values:

      ingress:
        enabled: true
        host: crud.localhost
        basePath: ""

      serviceMonitor:
        enabled: true

        prometheusOperatorReleaseName: monitoring-stack
        # TODO => prometheusRelease: monitoring-stack

      microservices:

        - microserviceName: item-creator
          microserviceReplicas: 1
          clientMaxIterations: 10
          clientIntervalInMinutes: 1

        - microserviceName: item-reader
          microserviceReplicas: 1
          clientMaxIterations: 10
          clientIntervalInMinutes: 2

        - microserviceName: item-updater
          microserviceReplicas: 1
          clientMaxIterations: 10
          clientIntervalInMinutes: 3

        - microserviceName: item-deleter
          microserviceReplicas: 1
          clientMaxIterations: 10
          clientIntervalInMinutes: 4
