{
 "title": "Python CRUD",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Successful requests by method",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (pycrud_http_requests_total{status=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Item count over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "expr": "sum(pycrud_items_total)", "legendFormat": "Item count" }
   ]
  },
  {
   "title": "Current item count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pycrud_items_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average database operation latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (operation) (rate(pycrud_database_latency_seconds_sum[5m])) * 1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}