microservices:

  - microserviceName: item-creator
    microserviceReplicas: 2
    clientMaxIterations: 50
    clientIntervalInMinutes: 3

  - microserviceName: item-reader
    microserviceReplicas: 2
    clientMaxIterations: 50
    clientIntervalInMinutes: 1

  - microserviceName: item-updater
    microserviceReplicas: 2
    clientMaxIterations: 50
    clientIntervalInMinutes: 2

  - microserviceName: item-deleter
    microserviceReplicas: 2
    clientMaxIterations: 50
    clientIntervalInMinutes: 4

logLevel: INFO

ingress:
  enabled: false
  host: localhost
  basePath: /crud

serviceMonitor:
  enabled: false
  prometheusRelease: prometheus
