{{ $releaseName := .Release.Name }}
{{ $releaseNamespace := .Release.Namespace }}
{{ $logLevel := .Values.logLevel }}
{{ range .Values.microservices }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ printf "%s-%s" $releaseName .microserviceName }}
  labels:
    app: {{ printf "%s-%s" $releaseName .microserviceName }}

spec:
  selector:
    matchLabels:
      app: {{ printf "%s-%s" $releaseName .microserviceName }}

  replicas: {{ .microserviceReplicas }}

  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" $releaseName .microserviceName }}

    spec:
      containers:
      - name: {{ .microserviceName }}

        image: {{ printf "docker.io/adarlan/crudify-%s:master" .microserviceName }}
        # TODO tag for development environment

        ports:
        - name: web
          containerPort: 8080
        - name: metrics
          containerPort: 9100

        env:
        - name: LOG_LEVEL
          value: {{ $logLevel }}
        - name: MONGO_HOST
          value: {{ printf "%s-mongodb.%s.svc.cluster.local" $releaseName $releaseNamespace }}
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-mongodb-credentials" $releaseName }}
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-mongodb-credentials" $releaseName }}
              key: MONGO_PASSWORD
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-mongodb-credentials" $releaseName }}
              key: MONGO_DATABASE

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

        livenessProbe:
          httpGet:
            port: web
            path: /healthz
          initialDelaySeconds: 30
          periodSeconds: 10
---
{{ end }}
