apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: administrator
  labels:
    selection: rbac
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: administrator
  labels:
    selection: rbac
roleRef:
  kind: ClusterRole
  name: administrator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: "Jane Ops"
