apiVersion: v1
kind: Service
metadata:
  name:  {{ printf "%s-mongodb" .Release.Name }}
  labels:
    app: {{ printf "%s-mongodb" .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ printf "%s-mongodb" .Release.Name }}
