{{ if .Values.serviceMonitor.enabled }}
{{ $releaseName := .Release.Name }}
{{ $prometheusRelease := .Values.serviceMonitor.prometheusRelease }}
{{ range .Values.microservices }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ printf "%s-%s" $releaseName .microserviceName }}
  labels:
    app: {{ printf "%s-%s" $releaseName .microserviceName }}

    # NOTE Prometheus Operator automatically generates monitoring target configuration based on this label
    release: {{ $prometheusRelease }}

spec:
  selector:
    matchLabels:
      app: {{ printf "%s-%s" $releaseName .microserviceName }}

  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s

---
{{ end }}
{{ end }}
