apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: security-stack
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/adarlan/k8slab.git
    path: helm-charts/security-stack
    targetRevision: master
    helm:
      releaseName: security
      valuesObject:
        ingress-nginx:
          enabled: true

  destination:
    name: in-cluster
    namespace: security

  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
