apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: hello-world
        image: {{ printf "docker.io/adarlan/hello-world:%s" .Values.imageTag }}
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
          httpGet:
            port: web
            path: /healthz
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: config-files
          subPath: index.html
      volumes:
      - name: config-files
        configMap:
          name: {{ .Release.Name }}
