trivy:
  server:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
        # ephemeral-storage: "2Gi"
      limits:
        cpu: 500m
        memory: 512Mi
      # ephemeral-storage: "2Gi"
