apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}

  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web

  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
