apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-hello-world
  labels:
    app: {{ .Release.Name }}-hello-world

spec:
  selector:
    app: {{ .Release.Name }}-hello-world

  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web

  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
