microservices:
  - microserviceName: item-creator
  - microserviceName: item-reader
  - microserviceName: item-updater
  - microserviceName: item-deleter

logLevel: INFO

ingressHost: crud.localhost
ingressBasePath: "/crud"
