on:
  workflow_call:
    inputs:
      build_context:
        description: The build context directory used by Docker during the image build process
        type: string
        default: '.'
      options:
        type: string
        default: ''

jobs:
  scan:
    name: Trivy vulnerability scan
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker build
        working-directory: ${{ inputs.build_context }}
        run: docker build -t temp-image ${{ inputs.options }} .

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'temp-image'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          # TODO severity: 'CRITICAL,HIGH'
