on:
  workflow_call:
    inputs:
      full_image_name:
        description: The complete name of the Docker image, including the repository, image name, and tag
        type: string
        required: true
      build_context:
        description: The build context directory used by Docker during the image build process
        type: string
        default: "."
    secrets:
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true

jobs:
  build_and_push:
    name: Build and push the Docker image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      - name: Build Docker image
        working-directory: ${{ inputs.build_context }}
        run: docker build -t ${{ inputs.full_image_name }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ inputs.full_image_name }}

# TODO multi-arch build
