name: Terraform Module Test

on:
  workflow_call:
    inputs:
      context_path:
        description: The path of the Terraform module within the repository
        type: string
        default: "."

jobs:
  test:
    name: Validate Terraform configuration
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.3

      - name: Terraform formatting check
        working-directory: ${{ inputs.context_path }}
        run: terraform fmt -check -recursive -diff

      - name: Terraform init
        working-directory: ${{ inputs.context_path }}
        run: terraform init -input=false -backend=false

      - name: Terraform validate
        working-directory: ${{ inputs.context_path }}
        run: terraform validate
