on:
  workflow_call:
    inputs:
      context_path:
        description: The path of the Terraform module within the repository
        type: string
        default: "."

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.3
      - name: fmt-check
        run: terraform -chdir=${{ inputs.context_path }} fmt -check -recursive -diff
      - name: init
        run: terraform -chdir=${{ inputs.context_path }} init -input=false -backend=false
      - name: validate
        run: terraform -chdir=${{ inputs.context_path }} validate
