name: EKS Terraform Module

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform-module:
    uses: adarlan/k8slab/.github/reusable-workflows/terraform-module.yaml
