name: EKS Cluster (Terraform Module)

on:
  push:
    branches:
      - '**'
    paths:
      - 'eks-cluster/**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'eks-cluster/**'
  workflow_dispatch:

jobs:
  terraform-module-test:
    name: Terraform Module Test
    uses: ./.github/workflows/.terraform-module-test.yaml
    with:
      context_path: eks-cluster
