name: Python App

on:
  push:
    branches:
      - 'master'
    paths:
      - 'python-app/**'
      - '.github/workflows/**'

jobs:
  docker-image:
    name: Python App Docker Image
    uses: .github/workflows/.docker-image.yaml
    with:
      full_image_name: adarlan/python-app:latest
      build_context: python-app
