name: Python App

on:
  push:
    branches:
      - '**'
    paths:
      - 'python-app/**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'python-app/**'
  workflow_dispatch:

jobs:
  docker-image-test:
    name: Docker image test
    uses: ./.github/workflows/.docker-image-test.yaml
    with:
      build_context: python-app

  docker-image-push:
    name: Docker image push
    needs: docker-image-test
    uses: ./.github/workflows/.docker-image-push.yaml
    with:
      build_context: python-app
      full_image_name: adarlan/python-app:${{ github.ref_name }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
