name: Python App

on:
  push:
    branches:
      - 'master'
    # paths:
    #   - 'python-app/**'
    #   - '.github/workflows/**'

jobs:
  docker-image:
    name: Python App Docker Image
    uses: adarlan/k8slab/.github/workflows/.docker-image.yaml@master
    with:
      full_image_name: adarlan/python-app:latest
      build_context: python-app
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
